{{- if .Values.postgres.local -}}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: sink-database-cluster
spec:
  patroni:
    pg_hba:
      - local all postgres  ident
      - host all all 0.0.0.0/0 md5
      - host replication replicator 0.0.0.0/0 md5
  teamId: "sink"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    sinkuser:  # database owner
      - superuser
      - createdb
  postgresql:
    version: "15"
{{- end -}}
