apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-connect.fullname" . }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9092
  selector:
    {{- include "kafka-connect.selectorLabels" . | nindent 4 }}
