{{- range .Values.kafka.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ include "kafka-cluster.fullname" . }}
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
{{- end }}
