
connect:
  image: "localhost:5001/optin-poc-kafka-connector:4.2.0"
    # Overrides the image tag whose default is the chart appVersion.
  bootstrapServer: kafka-cluster-kafka-bootstrap:9092
#  tls:
#    trustedCertificates:
#      - secretName: my-cluster-cluster-ca-cert
#        certificate: ca.crt
postgres:
  local: true

  sink:
    deploymentActive: true
    name:  postgres-sink
    connection:
      host: "sink-database-cluster"
      port: 5432
      database: "postgres"
      user: "sinkuser"
      password: "G2hhEk80e67XSLgsFecqsJmXq5siYSHYoZx6gUPkUqHBQYgn1nYhn10DIFPDSLpA"
    topics: consent.preference.sink
    autoCreate: true
    autoEvolve: true
    deleteEnabled: true
    insertMode: upsert
    pkMode: record_key
    pkFields: customerId,target
    valueConverter: "org.apache.kafka.connect.json.JsonConverter"
    keyConverter: "org.apache.kafka.connect.json.JsonConverter"
    tableNameFormat: channel_consents
    fieldsWhitelist: channel,target,source,time
    enableValueSchema: true
    enableKeySchema: true
    behaviorOnNullValues: delete



replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 9092
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        backend:
          serviceName: chart-example.local
          servicePort: 80
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}

