/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Customer Info Service
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { GrantConsentExBody, RevokeConsentExBody } from './model';

/**
 * @summary Give consent for advertisment in the given channel
 */
export const grantConsentEx = <TData = AxiosResponse<unknown>>(
  customerId: string,
  channel: string,
  grantConsentExBody: GrantConsentExBody,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(
    `/customer/${customerId}/consent/${channel}`,
    grantConsentExBody,
    options
  );
};

/**
 * @summary Revoke consent for advertisment in the given channel
 */
export const revokeConsentEx = <TData = AxiosResponse<unknown>>(
  customerId: string,
  channel: string,
  revokeConsentExBody: RevokeConsentExBody,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(
    `/customer/${customerId}/revoke/${channel}`,
    revokeConsentExBody,
    options
  );
};

export type GrantConsentExResult = AxiosResponse<unknown>;
export type RevokeConsentExResult = AxiosResponse<unknown>;
