/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Customer Info Service
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { GrantConsentBody, RevokeConsentBody } from './model';

/**
 * @summary Give consent for advertisment in the given channel
 */
export const grantConsent = <TData = AxiosResponse<unknown>>(
  customerId: string,
  channel: string,
  grantConsentBody: GrantConsentBody,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(
    `/customer/${customerId}/consent/${channel}`,
    grantConsentBody,
    options
  );
};

/**
 * @summary Revoke consent for advertisment in the given channel
 */
export const revokeConsent = <TData = AxiosResponse<unknown>>(
  customerId: string,
  channel: string,
  revokeConsentBody: RevokeConsentBody,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(
    `/customer/${customerId}/revoke/${channel}`,
    revokeConsentBody,
    options
  );
};

export type GrantConsentResult = AxiosResponse<unknown>;
export type RevokeConsentResult = AxiosResponse<unknown>;
