
ingress:
  enabled: false

kafka:
  externalListener: false

  users:
    - name: pocclient

letsEncrypt:
  enabled: false

replicaCount: 1

serviceAccount:
  create: true


service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
