/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Customer Info Service
 * OpenAPI spec version: 1.0.0
 */
import type { Customer } from './customer';

export type Customers = Customer[];
