/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Aggregate Info Service
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelConsent } from './channelConsent';

export interface CustomerConsent {
  customerId: string;
  channelConsents: ChannelConsent[];
}
