/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Database Info Service
 * OpenAPI spec version: 1.0.0
 */

export type RevokeConsentBody = {
  target: string;
  customerId: string;
  channel: string;
};
