/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Database Info Service
 * OpenAPI spec version: 1.0.0
 */

export type SinkDatabaseItem = {
  /** The ID of the customer */
  customerId: string;
  /** The communication channel */
  channel: string;
  /** The target of the communication */
  target: string;
  /** The source of the communication */
  source: string;
  /** The time of the communication in Unix timestamp format */
  time: string;
};
