/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Database Info Service
 * OpenAPI spec version: 1.0.0
 */
import type { SinkDatabaseItem } from './sinkDatabaseItem';

export type SinkDatabase = SinkDatabaseItem[];
