openapi: "3.0.0"
info:
  version: 1.0.0
  title: Aggregate Info Service
  license:
    name: MIT
paths:
  /customer-consents:
    get:
      summary: Get all Customer Consents
      operationId: getAggregate
      tags:
        - aggregate
      responses:
        '200':
          description: A list of Customer Consents
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerConsents"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ChannelConsent:
      type: object
      required:
        - channel
        - consentDate
        - source
        - target
      properties:
        channel:
          type: string
        consentDate:
          type: string
        source:
          type: string
        target:
          type: string
    CustomerConsent:
      type: object
      required:
        - customerId
        - channelConsents
      properties:
        customerId:
          type: string
        channelConsents:
          type: array
          items:
            $ref: "#/components/schemas/ChannelConsent"
    CustomerConsents:
      type: array
      items:
        $ref: "#/components/schemas/CustomerConsent"

