apiVersion: v1
kind: Service
metadata:
  name: {{ include "opt-in-out.fullname" . }}
  labels:
    {{- include "opt-in-out.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "opt-in-out.selectorLabels" . | nindent 4 }}
