server.port: 8085
spring:
  kafka:
    producer:
      bootstrap-servers: "localhost:32100"
      client-id: "client1-xy"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.StringSerializer"
    consumer:
      bootstrap-servers: "localhost:32100"
      enable-auto-commit: false
      group-id: "group1-xy"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true
