openapi: 3.0.0
info:
  version: 1.0.0
  title: Database Info Service
  license:
    name: MIT
paths:
  /api/database:
    get:
      summary: Get customer consents
      operationId: getSinkDatabase
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sinkDatabase'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - database
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    sinkDatabase:
      type: array
      items:
        type: object
        required:
          - customerId
          - channel
          - target
          - source
          - time
        properties:
          customerId:
            type: string
            description: The ID of the customer
          channel:
            type: string
            description: The communication channel
          target:
            type: string
            description: The target of the communication
          source:
            type: string
            description: The source of the communication
          time:
            type: string
            description: The time of the communication in Unix timestamp format
